/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import modelos.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO ULTRA 5
 */
public class AdministrarClientes extends javax.swing.JFrame {
    
    private Banco banco;
    private Empleado empleado;
    private Administrador administrador;

    /**
     * Creates new form AdministrarClientes
     */
    public AdministrarClientes() {
        initComponents();
    }
    public AdministrarClientes(Banco banco, Empleado empleado) {
        this.banco = banco;
        this.empleado = empleado;
        initComponents();
        cargarClientes();
    }
    public AdministrarClientes(Banco banco, Administrador administrador) {
        this.banco = banco;
        this.administrador = administrador;
        initComponents();
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList<>();
        CrearCliente = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloLista.setText("Lista de Clientes");

        ListaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaClientes);

        CrearCliente.setText("Crear Cliente");
        CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearClienteMouseClicked(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(TituloLista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CrearCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Volver)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CrearCliente)
                .addGap(18, 18, 18)
                .addComponent(Volver)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        // TODO add your handling code here:
        if (empleado != null) {
            MenuEmpleado ME = new MenuEmpleado(banco, empleado);
            ME.setLocationRelativeTo(this);
            ME.setVisible(true);
            this.dispose();
        } else if (administrador != null) {
            MenuAdministrador MA = new MenuAdministrador(banco, administrador);
            MA.setLocationRelativeTo(this);
            MA.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_VolverMouseClicked

    private void CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClienteMouseClicked
        // TODO add your handling code here:
        try {
        String dni = JOptionPane.showInputDialog("DNI");
        String nombre = JOptionPane.showInputDialog("Nombre");
        String direccion = JOptionPane.showInputDialog("Direccion");
        String telefono = JOptionPane.showInputDialog("Telefono");
        String email = JOptionPane.showInputDialog("Email");
        String usuario = JOptionPane.showInputDialog("Usuario");
        String contraseña = JOptionPane.showInputDialog("Clave");

        //Crea y retorna el nuevo cliente creado
        Cliente nuevo = new Cliente(dni, nombre, direccion, telefono, email, usuario, contraseña);
        banco.registrarCliente(nuevo);
        cargarClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearClienteMouseClicked
    private void cargarClientes() {
        DefaultListModel<String> clientes = new DefaultListModel<>();
        ArrayList<String> datos = banco.listarClientes();
        
        for (int i = 0; i < datos.size(); i++) {
            clientes.addElement(datos.get(i));
        }
        
        ListaClientes.setModel(clientes);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministrarClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearCliente;
    private javax.swing.JList<String> ListaClientes;
    private javax.swing.JLabel TituloLista;
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
