/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import modelos.*;
import java.util.ArrayList;

/**
 *
 * @author LENOVO ULTRA 5
 */
public class Inicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());
    private Banco banco;

        
    /**
     * Creates new form Inicio
     */
    public Inicio(Banco banco) {
        try {
            this.banco = banco;
            initComponents();
            Empleado emp = new Empleado("61761556","Diego Cahuana","Yura - Arequipa","997134305","dcauhana@banco.com","DegoX", "Camargo");
            Cliente cliente = new Cliente("60060857","Brayan Motta","Socabaya - Arequipa","945846028","brayan@gmail.com","bmotta","CHOCA");
            Administrador adm = new Administrador("34628123", "Atuncito", "Lima - San Isidro", "963852741", "at@gmail.com", "atun", "shh");
            ArrayList<Cliente> cli = new ArrayList<>();
            Cuenta cuenta = emp.crearCuenta(cli, 1, 500);
            cliente.agregarCuenta(cuenta);
            banco.cuentas.add(cuenta);
            banco.empleados.add(emp);
            banco.clientes.add(cliente);
            banco.administradores.add(adm);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Administrador = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Empleado = new javax.swing.JButton();
        Cliente = new javax.swing.JButton();
        Instrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Administrador.setBackground(new java.awt.Color(0, 153, 255));
        Administrador.setText("Administrador");
        Administrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginAdministrador(evt);
            }
        });
        Administrador.addActionListener(this::AdministradorActionPerformed);
        bg.add(Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        Titulo.setText("SISTEMA DEL BANCO");
        bg.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 190, 20));

        Empleado.setBackground(new java.awt.Color(0, 153, 255));
        Empleado.setText("Empleado");
        Empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginEmpleado(evt);
            }
        });
        Empleado.addActionListener(this::EmpleadoActionPerformed);
        bg.add(Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        Cliente.setBackground(new java.awt.Color(0, 153, 255));
        Cliente.setText("Cliente");
        Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginCliente(evt);
            }
        });
        Cliente.addActionListener(this::ClienteActionPerformed);
        bg.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        Instrucciones.setText("SELECCIONE EL TIPO DE USUARIO CON EL QUE DESEA INGRESAR");
        bg.add(Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginAdministrador(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginAdministrador
        // TODO add your handling code here:
        Login login = new Login(banco, "A");
        login.setLocationRelativeTo(this);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginAdministrador

    private void LoginEmpleado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginEmpleado
        // TODO add your handling code here:
        Login login = new Login(banco, "E");
        login.setLocationRelativeTo(this);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginEmpleado

    private void LoginCliente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginCliente
        // TODO add your handling code here:
        Login login = new Login(banco, "C");
        login.setLocationRelativeTo(this);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginCliente

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteActionPerformed

    private void AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministradorActionPerformed

    private void EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Banco banco = new Banco();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio(banco).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Administrador;
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Empleado;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
