/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import modelos.*;

/**
 *
 * @author LENOVO ULTRA 5
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private Banco banco;
    private String tipo;
    
    /**
     * Creates new form LoginCliente
     */
    public Login() {
        initComponents();
    }
    public Login(Banco banco, String tipo) {
        this.tipo = tipo;
        this.banco = banco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        Usuario = new javax.swing.JLabel();
        UsuarioField = new javax.swing.JTextField();
        Clave = new javax.swing.JLabel();
        ClaveField = new javax.swing.JPasswordField();
        Loguarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Volver(evt);
            }
        });

        Usuario.setText("Usuario:");

        UsuarioField.setText("Usuario");

        Clave.setText("Clave:");

        ClaveField.setText("jPasswordField1");

        Loguarse.setLabel("Loguearse");
        Loguarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoguarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Volver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Loguarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(Usuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(Clave))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClaveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario)
                .addGap(18, 18, 18)
                .addComponent(UsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Clave)
                .addGap(18, 18, 18)
                .addComponent(ClaveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(Loguarse))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Volver
        // TODO add your handling code here:
        Inicio ini = new Inicio(banco);
        ini.setLocationRelativeTo(this);
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volver

    private void LoguarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoguarseMouseClicked
        // TODO add your handling code here:
        String usuario = UsuarioField.getText();
        switch (tipo) {
            case "A" -> {
                try {
                    Administrador administradorLogueado = banco.seleccionarAdministradorPorUsuario(usuario);
                    try {
                        char[] claveString = ClaveField.getPassword();
                        String clave = new String(claveString);
                        administradorLogueado.login(usuario, clave);
                        MenuAdministrador MA = new MenuAdministrador(banco, administradorLogueado);
                        MA.setLocationRelativeTo(this);
                        MA.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Clave incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No existe ese administrador", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            case "C" -> {
                try {
                    Cliente clienteLogueado = banco.seleccionarClientePorUsuario(usuario);
                    try {
                        char[] claveString = ClaveField.getPassword();
                        String clave = new String(claveString);
                        clienteLogueado.login(usuario, clave);
                        MenuCliente MC = new MenuCliente(banco, clienteLogueado);
                        MC.setLocationRelativeTo(this);
                        MC.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Clave incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No existe ese cliente", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            case "E" -> {
                try {
                    Empleado empleadoLogueado = banco.seleccionarEmpleadoPorUsuario(usuario);
                    try {
                        char[] claveString = ClaveField.getPassword();
                        String clave = new String(claveString);
                        empleadoLogueado.login(usuario, clave);
                        MenuEmpleado ME = new MenuEmpleado(banco, empleadoLogueado);
                        ME.setLocationRelativeTo(this);
                        ME.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Clave incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No existe ese empleado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }        
    }//GEN-LAST:event_LoguarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JPasswordField ClaveField;
    private javax.swing.JButton Loguarse;
    private javax.swing.JLabel Usuario;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JButton Volver;
    // End of variables declaration//GEN-END:variables
}
