/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import modelos.*;

/**
 *
 * @author LENOVO ULTRA 5
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private Banco banco;
    private String tipo;
    
    /**
     * Creates new form LoginCliente
     */
    public Login() {
        initComponents();
    }
    public Login(Banco banco, String tipo) {
        this.tipo = tipo;
        this.banco = banco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        UsuarioField = new javax.swing.JTextField();
        Usuario1 = new javax.swing.JLabel();
        ClaveField = new javax.swing.JPasswordField();
        Loguarse = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("© 2025 Banco Chanchito. Todos los derechos reservados.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 450));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        Volver.setBackground(new java.awt.Color(255, 153, 51));
        Volver.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_atras_1.png"))); // NOI18N
        Volver.setText("Volver");
        Volver.setBorder(null);
        Volver.setBorderPainted(false);
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Volver(evt);
            }
        });
        Volver.addActionListener(this::VolverActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Usuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario.setText("Usuario:");

        UsuarioField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsuarioField.setText("Usuario");
        UsuarioField.addActionListener(this::UsuarioFieldActionPerformed);

        Usuario1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario1.setText("Contraseña:");

        ClaveField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClaveField.setText("jPasswordField1");

        Loguarse.setBackground(new java.awt.Color(255, 153, 51));
        Loguarse.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Loguarse.setForeground(new java.awt.Color(255, 255, 255));
        Loguarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_delante_1.png"))); // NOI18N
        Loguarse.setText("Ingresar");
        Loguarse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Loguarse.setBorderPainted(false);
        Loguarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Loguarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoguarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(UsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(ClaveField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addComponent(Usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Loguarse, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Usuario)
                .addGap(18, 18, 18)
                .addComponent(UsuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario1)
                .addGap(18, 18, 18)
                .addComponent(ClaveField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Loguarse, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("© 2025 Banco Chanchito. Todos los derechos reservados.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Volver(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Volver
        // TODO add your handling code here:
        Inicio ini = new Inicio(banco);
        ini.setLocationRelativeTo(this);
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volver

    private void LoguarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoguarseMouseClicked
        // TODO add your handling code here:
        String usuario = UsuarioField.getText();
        switch (tipo) {
            case "A" -> {
                try {
                    Administrador administradorLogueado = banco.seleccionarAdministradorPorUsuario(usuario);
                    try {
                        char[] claveString = ClaveField.getPassword();
                        String clave = new String(claveString);
                        administradorLogueado.login(usuario, clave);
                        MenuAdministrador MA = new MenuAdministrador(banco, administradorLogueado);
                        MA.setLocationRelativeTo(this);
                        MA.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Clave incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            case "C" -> {
                try {
                    Cliente clienteLogueado = banco.seleccionarClientePorUsuario(usuario);
                    try {
                        char[] claveString = ClaveField.getPassword();
                        String clave = new String(claveString);
                        clienteLogueado.login(usuario, clave);
                        MenuCliente MC = new MenuCliente(banco, clienteLogueado);
                        MC.setLocationRelativeTo(this);
                        MC.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Clave incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No existe ese cliente", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
            case "E" -> {
                try {
                    Empleado empleadoLogueado = banco.seleccionarEmpleadoPorUsuario(usuario);
                    try {
                        char[] claveString = ClaveField.getPassword();
                        String clave = new String(claveString);
                        empleadoLogueado.login(usuario, clave);
                        MenuEmpleado ME = new MenuEmpleado(banco, empleadoLogueado);
                        ME.setLocationRelativeTo(this);
                        ME.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Clave incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No existe ese empleado", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }        
    }//GEN-LAST:event_LoguarseMouseClicked

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverActionPerformed

    private void UsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClaveField;
    private javax.swing.JButton Loguarse;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
