/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import modelos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO ULTRA 5
 */
public class MenuAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAdministrador.class.getName());
    private Banco banco;
    private Administrador administrador;
    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
    }
    public MenuAdministrador(Banco banco, Administrador administrador) {
        this.banco = banco;
        this.administrador = administrador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Permisos = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JButton();
        AdministrarClientes = new javax.swing.JButton();
        Retiro = new javax.swing.JButton();
        Deposito = new javax.swing.JButton();
        MostrarDatos = new javax.swing.JButton();
        AdministrarEmpleados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Permisos.setText("Mostrar Permisos");
        Permisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PermisosMouseClicked(evt);
            }
        });
        Permisos.addActionListener(this::PermisosActionPerformed);

        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        CerrarSesion.addActionListener(this::CerrarSesionActionPerformed);

        AdministrarClientes.setText("Administrar clientes");
        AdministrarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrarClientesMouseClicked(evt);
            }
        });

        Retiro.setText("Registrar Retiro");
        Retiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetiroMouseClicked(evt);
            }
        });

        Deposito.setText("Registrar Deposito");
        Deposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepositoMouseClicked(evt);
            }
        });

        MostrarDatos.setText("Mostrar Datos");

        AdministrarEmpleados.setText("Administrar empleados");
        AdministrarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrarEmpleadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CerrarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MostrarDatos)
                            .addComponent(Permisos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdministrarClientes)
                            .addComponent(Deposito)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdministrarEmpleados)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Retiro)
                                .addGap(24, 24, 24)))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AdministrarClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Retiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Deposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdministrarEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(MostrarDatos)
                .addGap(33, 33, 33)
                .addComponent(Permisos)
                .addGap(38, 38, 38)
                .addComponent(CerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermisosActionPerformed

    private void PermisosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PermisosMouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, administrador.mostrarPermisos(), "Detalles", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_PermisosMouseClicked

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        // TODO add your handling code here:
        Inicio ini = new Inicio(banco);
        ini.setLocationRelativeTo(this);
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked

    private void AdministrarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrarClientesMouseClicked
        // TODO add your handling code here:
        AdministrarClientes AC = new AdministrarClientes(banco, administrador);
        AC.setLocationRelativeTo(this);
        AC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdministrarClientesMouseClicked

    private void RetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetiroMouseClicked
        // TODO add your handling code here:
        try {
            String codigoCliente = JOptionPane.showInputDialog("Codigo del cliente");
            Cliente cliente = banco.seleccionarClientePorID(codigoCliente);
            String codigoCuenta = JOptionPane.showInputDialog("Codigo de la cuenta");
            Cuenta cuenta = cliente.seleccionarCuenta(codigoCuenta);
            float monto = Float.parseFloat(JOptionPane.showInputDialog("Ingrese el monto a retirar"));
            if (cuenta.getSaldo() < monto) {
                throw new Exception("No hay tanto dinero en la cuenta");
            }
            Retiro r = administrador.registrarRetiro(cuenta, monto, cliente);
            r.procesar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RetiroMouseClicked

    private void DepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepositoMouseClicked
        // TODO add your handling code here:
        try {
            String codigoCliente = JOptionPane.showInputDialog("Codigo del cliente");
            Cliente cliente = banco.seleccionarClientePorID(codigoCliente);
            String codigoCuenta = JOptionPane.showInputDialog("Codigo de la cuenta");
            Cuenta cuenta = cliente.seleccionarCuenta(codigoCuenta);
            float monto = Float.parseFloat(JOptionPane.showInputDialog("Ingrese el monto a depositar"));
            Deposito d = administrador.registrarDeposito(cuenta, monto, cliente);
            d.procesar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DepositoMouseClicked

    private void AdministrarEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrarEmpleadosMouseClicked
        // TODO add your handling code here:
        AdministrarEmpleados AE = new AdministrarEmpleados(banco, administrador);
        AE.setLocationRelativeTo(this);
        AE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdministrarEmpleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministrarClientes;
    private javax.swing.JButton AdministrarEmpleados;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton Deposito;
    private javax.swing.JButton MostrarDatos;
    private javax.swing.JButton Permisos;
    private javax.swing.JButton Retiro;
    // End of variables declaration//GEN-END:variables
}
