/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import modelos.*;

/**
 *
 * @author LENOVO ULTRA 5
 */
public class ResumenCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResumenCuenta.class.getName());
    private Cuenta cuenta;
    private Banco banco;
    private Cliente cliente;
    
    /**
     * Creates new form ResumenCuenta
     */
    public ResumenCuenta() {
        initComponents();
    }
    public ResumenCuenta(Banco banco, Cliente cliente, Cuenta cuenta) {
        this.banco = banco;
        this.cliente = cliente;
        this.cuenta = cuenta;
        initComponents();
        Titulo.setText("Mostrando datos de la cuenta: "+cuenta.getNumero());
        Datos.setText(cuenta.mostrarResumen());
        mostrarTransacciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        Depositos = new javax.swing.JButton();
        Retiros = new javax.swing.JButton();
        Todo = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Datos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("jLabel1");

        Lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Lista);

        Depositos.setText("Filtrar por Depositos");
        Depositos.addActionListener(this::DepositosActionPerformed);

        Retiros.setText("Filtrar por Retiros");
        Retiros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetirosMouseClicked(evt);
            }
        });

        Todo.setText("Mostrar todo");
        Todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TodoMouseClicked(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        Datos.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Datos)
                    .addComponent(Volver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Depositos)
                    .addComponent(Retiros)
                    .addComponent(Todo))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Depositos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Retiros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Todo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Datos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(Volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositosActionPerformed

    private void TodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TodoMouseClicked
        // TODO add your handling code here:
        mostrarTransacciones();
    }//GEN-LAST:event_TodoMouseClicked

    private void RetirosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirosMouseClicked
        // TODO add your handling code here:
        DefaultListModel<String> transacciones = new DefaultListModel<>();
        ArrayList<String> resumen = cuenta.mostrarMovimientos();
        
        for (int i = 0; i < resumen.size(); i++) {
            transacciones.addElement(resumen.get(i));
        }
        
        Lista.setModel(transacciones);
    }//GEN-LAST:event_RetirosMouseClicked

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        // TODO add your handling code here:
        ResumenCuentas res = new ResumenCuentas(banco, cliente);
        res.setLocationRelativeTo(this);
        res.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverMouseClicked

    /**
     * @param args the command line arguments
     */
    private void mostrarTransacciones() {
        DefaultListModel<String> transacciones = new DefaultListModel<>();
        ArrayList<String> resumen = cuenta.mostrarMovimientos();
        
        for (int i = 0; i < resumen.size(); i++) {
            transacciones.addElement(resumen.get(i));
        }
        
        Lista.setModel(transacciones);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ResumenCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datos;
    private javax.swing.JButton Depositos;
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton Retiros;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Todo;
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
