/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bancoChanchito;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author ASUS
 */
public class VentanaMenuCliente extends javax.swing.JFrame {
    private modelos.Banco banco;
    private modelos.Cliente cliente;
    /**
     * Creates new form VentanaMenuCliente
     */
    public VentanaMenuCliente() {
        initComponents();
    }
    public VentanaMenuCliente(modelos.Banco banco, modelos.Cliente cliente) {
        this.banco = banco;
        this.cliente = cliente;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menú Cliente - " + cliente.getNombre());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnConsultarCuentas = new javax.swing.JButton();
        btnVerMovimientos = new javax.swing.JButton();
        btnConsultarSaldo = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTitulo.setText("MENÚ CLIENTE");

        btnConsultarCuentas.setText("Consultar resumen de cuentas");
        btnConsultarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCuentasActionPerformed(evt);
            }
        });

        btnVerMovimientos.setText("Ver movimientos");
        btnVerMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMovimientosActionPerformed(evt);
            }
        });

        btnConsultarSaldo.setText("Consultar saldo total");
        btnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSaldoActionPerformed(evt);
            }
        });

        btnPermisos.setText("Ver permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVerMovimientos)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPermisos)
                        .addGap(196, 196, 196))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarSaldo)
                            .addComponent(btnConsultarCuentas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnCerrarSesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarCuentas)
                .addGap(18, 18, 18)
                .addComponent(btnVerMovimientos)
                .addGap(26, 26, 26)
                .addComponent(btnConsultarSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPermisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCuentasActionPerformed
         if (cliente.getCuentas().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No tiene cuentas registradas",
                "Sin cuentas",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        StringBuilder resumen = new StringBuilder();
        resumen.append("=== CUENTAS DEL CLIENTE ").append(cliente.getNombre()).append(" ===\n\n");
        
        for (modelos.Cuenta c : cliente.getCuentas()) {
            resumen.append("Número: ").append(c.getNumero()).append("\n");
            resumen.append("Tipo: ").append(c.getTipo()).append("\n");
            resumen.append("Saldo: S/ ").append(String.format("%.2f", c.getSaldo())).append("\n");
            resumen.append("─────────────────────────\n");
        }
        
        JTextArea textArea = new JTextArea(resumen.toString());
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(400, 300));
        
        JOptionPane.showMessageDialog(
            this,
            scrollPane,
            "Resumen de Cuentas",
            JOptionPane.INFORMATION_MESSAGE
        );       // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarCuentasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea cerrar sesión?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
        );
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVerMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMovimientosActionPerformed
        if (cliente.getCuentas().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "No tiene cuentas registradas",
                "Sin cuentas",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        // Seleccionar cuenta
        String[] opciones = cliente.getCuentas().stream()
            .map(c -> c.getNumero() + " - S/ " + String.format("%.2f", c.getSaldo()))
            .toArray(String[]::new);
        
        String seleccion = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione una cuenta:",
            "Ver Movimientos",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );
        
        if (seleccion != null) {
            String numCuenta = seleccion.split(" - ")[0];
            modelos.Cuenta cuenta = cliente.getCuentas().stream()
                .filter(c -> c.getNumero().equals(numCuenta))
                .findFirst()
                .orElse(null);
            
            if (cuenta != null) {
                mostrarMovimientosCuenta(cuenta);
            }
        }                                                
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerMovimientosActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        String permisos = "=== PERMISOS DEL CLIENTE ===\n\n" +
                         "✓ Consultar resumen de sus cuentas\n" +
                         "✓ Ver movimientos de sus cuentas\n" +
                         "✓ Consultar saldo total\n";
        
        JOptionPane.showMessageDialog(
            this,
            permisos,
            "Permisos",
            JOptionPane.INFORMATION_MESSAGE
        );// TODO add your handling code here:
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void btnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActionPerformed
    float saldoTotal = cliente.getSaldoTotal();
        JOptionPane.showMessageDialog(
            this,
            "Saldo total en todas sus cuentas:\nS/ " + String.format("%.2f", saldoTotal),
            "Saldo Total",
            JOptionPane.INFORMATION_MESSAGE
        );        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarSaldoActionPerformed
    private void mostrarMovimientosCuenta(modelos.Cuenta cuenta) {
        if (cuenta.getMovimientos().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "La cuenta no tiene movimientos registrados",
                "Sin movimientos",
                JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        StringBuilder movimientos = new StringBuilder();
        movimientos.append("=== MOVIMIENTOS DE CUENTA ").append(cuenta.getNumero()).append(" ===\n\n");
        
        for (modelos.Transaccion t : cuenta.getMovimientos()) {
            movimientos.append("ID: ").append(t.getId()).append("\n");
            movimientos.append("Fecha: ").append(t.getFechaHora()).append("\n");
            movimientos.append("Monto: S/ ").append(String.format("%.2f", t.getMonto())).append("\n");
            movimientos.append("Tipo: ").append(t instanceof modelos.Deposito ? "DEPÓSITO" : "RETIRO").append("\n");
            movimientos.append("─────────────────────────\n");
        }
        
        JTextArea textArea = new JTextArea(movimientos.toString());
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setPreferredSize(new Dimension(450, 350));
        
        JOptionPane.showMessageDialog(
            this,
            scrollPane,
            "Movimientos de Cuenta",
            JOptionPane.INFORMATION_MESSAGE
        );
    }            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuCliente().setVisible(true);
            }
        });
    }
private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarCuentas;
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnVerMovimientos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

